from sqlalchemy import Column, String, Text, DateTime
from sqlalchemy.sql import func
from backend.db.database import Base


class UserProfile(Base):
    __tablename__ = "user_profile"

    # user_id is the primary key — one profile per user
    user_id = Column(String, primary_key=True)
    # JSON-encoded list of {question, answer} dicts
    qa_pairs = Column(Text, default="[]")
    # JSON-encoded list of question strings generated by Claude
    questions = Column(Text, default="[]")
    # Free-form text summary Claude generates from CV + answers
    search_context = Column(Text, default="")
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())
